debug: ${debug} # inherited from configurations/config.yaml

save_dir: data/flappy_bird
n_frames: 10 # TODO: increase later
validation_size: 10
h: &h 512
w: &w 288
reduce_reso_rate: 2
data_mean: 0.5
data_std: 0.5
external_cond_dim: 2
context_length: 1
frame_skip: 1
validation_multiplier: 4